name: conda_venv_hsi_prosail_inversion
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1
  - blas=1.0
  - blosc=1.21.6
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - certifi=2024.7.4
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.2.0
  - cycler=0.11.0
  - debugpy=1.8.3
  - decorator=5.1.1
  - et_xmlfile=1.1.0
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - expat=2.6.2
  - fonttools=4.51.0
  - freetype=2.12.1
  - freexl=2.0.0
  - gdal=3.9.1
  - geos=3.12.2
  - geotiff=1.7.3
  - glib=2.80.3
  - glib-tools=2.80.3
  - gst-plugins-base=1.24.6
  - gstreamer=1.24.6
  - icc_rt=2022.1.0
  - icu=73.2
  - importlib-metadata=8.2.0
  - importlib_metadata=8.2.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - kiwisolver=1.4.4
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libarchive=3.7.4
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang13=18.1.8
  - libcurl=8.9.1
  - libdeflate=1.20
  - libexpat=2.6.2
  - libffi=3.4.4
  - libgdal-core=3.9.1
  - libglib=2.80.3
  - libhwloc=2.11.1
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.3
  - libkml=1.3.0
  - liblapack=3.9.0
  - libogg=1.3.5
  - libpng=1.6.43
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialite=5.1.0
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libvorbis=1.3.7
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxml2=2.12.7
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - lzo=2.10
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - minizip=4.0.6
  - mkl=2023.2.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - msys2-conda-epoch=20160418
  - nest-asyncio=1.6.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openpyxl=3.1.5
  - openssl=3.3.1
  - packaging=24.1
  - pandas=2.2.2
  - parso=0.8.4
  - pcre2=10.44
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.0
  - platformdirs=4.2.2
  - ply=3.11
  - proj=9.4.1
  - prompt-toolkit=3.0.47
  - psutil=6.0.0
  - pthread-stubs=0.3
  - pthreads-win32=2.9.1
  - pure_eval=0.2.3
  - pybind11-abi=5
  - pygments=2.18.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - python=3.11.9
  - python-dateutil=2.9.0post0
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytz=2024.1
  - pywin32=306
  - pyzmq=26.0.3
  - qt-main=5.15.8
  - scipy=1.13.1
  - seaborn=0.13.2
  - setuptools=69.5.1
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tbb=2021.12.0
  - tk=8.6.13
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - uriparser=0.9.8
  - vc=14.2
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xerces-c=3.2.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.3.1
  - zstd=1.5.6
